ostatnie
coders-school/cpp-fundamentals pull request #654
Opened 2021-06-15 18:23 UTC by OlafKozak

pięknie

2021-06-15 18:24 UTC, ziobron commented
✅ CI Passed - Task: vector-of-shared-ptrs
🏅 Granted 5 XP for @OlafKozak

2021-06-16 13:12 UTC, nauka-programowania-MA requested changes

2021-06-16 13:12 UTC, nauka-programowania-MA commented on homework/vector-of-shared-ptrs/vectorFunctions.cpp
> +    std::vector<std::shared_ptr<int>> v;
Reserve memory when you know how many elements will be inside vector.

2021-06-16 13:12 UTC, nauka-programowania-MA commented on homework/vector-of-shared-ptrs/vectorFunctions.cpp
> +    for(int i=0;i<count;i++){
Add space after `if`, `for`, `while` `function` etc...

Add space between operator like `+` `-` `/` `:` `&&` etc..

2021-06-16 13:12 UTC, nauka-programowania-MA commented on homework/vector-of-shared-ptrs/vectorFunctions.cpp
> +void print(std::vector<std::shared_ptr<int>> v){
Pass by const refrence. Try always avoid copy.

2021-06-16 13:12 UTC, nauka-programowania-MA commented on homework/vector-of-shared-ptrs/vectorFunctions.cpp
> +    for(auto i : v){
const refrence. Try always avoid copy.

2021-06-16 13:12 UTC, nauka-programowania-MA commented on homework/vector-of-shared-ptrs/vectorFunctions.cpp
> +        std::cout << *i << std::endl;
Ptr may be null

2021-06-16 13:12 UTC, nauka-programowania-MA commented on homework/vector-of-shared-ptrs/vectorFunctions.cpp
> +void add10(std::vector<std::shared_ptr<int>> v){
Pass by const refrence. Try always avoid copy.

2021-06-16 13:12 UTC, nauka-programowania-MA commented on homework/vector-of-shared-ptrs/vectorFunctions.cpp
> +void sub10(std::vector<std::shared_ptr<int>> v){
Pass by const refrence. Try always avoid copy.

2021-06-16 13:12 UTC, nauka-programowania-MA commented on homework/vector-of-shared-ptrs/vectorFunctions.cpp
> +    if(a != nullptr) *a -= 10;
One command one line

2021-06-16 13:12 UTC, nauka-programowania-MA commented on homework/vector-of-shared-ptrs/vectorFunctions.cpp
> +        if(v[i] != nullptr) *v.at(i).get() += 10;
One command one line

2021-06-16 13:12 UTC, nauka-programowania-MA commented on homework/vector-of-shared-ptrs/vectorFunctions.cpp
> +        if(v[i] != nullptr) *v.at(i).get() += 10;
you don't need get. If you use *vector[i] it is enough

2021-06-16 13:12 UTC, nauka-programowania-MA commented on homework/vector-of-shared-ptrs/vectorFunctions.cpp
> +        if(v[i] != nullptr) *v.at(i).get() += 10;
if you use .at you should also handle exception for std:out_of_range

2021-06-30 19:43 UTC, closed without merging